name: Deploy to Elastic Beanstalk

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r portfolio_backend/requirements.txt

            - name: Create Application Version
              run: |
                  cd portfolio_backend
                  SHORT_COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  VERSION_LABEL="${TIMESTAMP}-${SHORT_COMMIT_HASH}"
                  echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

            - name: Deploy to Elastic Beanstalk
              run: |
                  cd portfolio_backend

                  # Initialize EB environment only if it's not already set up
                  eb init -p python-3.11 ${{ secrets.EB_APP_NAME }} --region eu-west-1
                  eb use ${{ secrets.EB_ENV }}
                  eb deploy --label $VERSION_LABEL --verbose
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
