name: Deploy Backend

on:
    push:
        paths:
            - "portfolio_backend/**"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install AWS Elastic Beanstalk CLI
              run: |
                  pip install awsebcli --upgrade

            - name: Install dependencies
              run: |
                  cd portfolio_backend
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Create Application Version
              run: |
                  cd portfolio_backend
                  SHORT_COMMIT_HASH=${{ github.sha::7 }}
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  ENV_NAME="${{ secrets.EB_ENV }}-${TIMESTAMP}-${SHORT_COMMIT_HASH}"
                  eb init -p python-3.11 $ENV_NAME --region eu-west-1 --platform "python-3.11"
                  eb use $ENV_NAME
                  eb create $VERSION_LABEL --verbose
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Deploy to Elastic Beanstalk
              run: |
                  cd portfolio_backend
                  eb deploy --label $VERSION_LABEL --verbose
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
