name: Deploy Backend

on:
    push:
        paths:
            - "portfolio_backend/**"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install AWS Elastic Beanstalk CLI
              run: |
                  pip install awsebcli --upgrade

            - name: Install dependencies
              run: |
                  cd portfolio_backend
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Deploy to Elastic Beanstalk
              run: |
                  cd portfolio_backend
                  eb init -p python-3.11 ${{ secrets.EB_ENV }} --region ${{ secrets.AWS_S3_REGION_NAME }} --platform "python-3.11"
                  eb use ${{ secrets.EB_ENV }}
                  sleep 5
                  eb deploy --verbose
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
                  AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
                  AWS_S3_CUSTOM_DOMAIN: ${{ secrets.AWS_S3_CUSTOM_DOMAIN }}
                  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
                  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
                  EMAIL_POR: ${{ secrets.EMAIL_PORT }}
